spring:
  application:
    name: server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql_db
    username: root
    password: root
  data:
    mongodb:
      database: mongo_db
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
