spring:
  application:
    name: server
    security:
      access-token:
        time-of-life: 5H
        key:
          private-key: classpath:key/access/private_key.pem
          public-key: classpath:key/access/public_key.pem
      refresh-token:
        time-of-life: 120H
        key:
          private-key: classpath:key/refresh/private_key.pem
          public-key: classpath:key/refresh/public_key.pem
      verify-token:
        time-of-life: 48H
        key:
          private-key: classpath:key/verify/private_key.pem
          public-key: classpath:key/verify/public_key.pem

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Ho_Chi_Minh
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: "send_mail: com.kltn.server.DTO.request.base.MailRequest, project-log: com.kltn.server.DTO.request.log.ChangeLogRequest, task-log: com.kltn.server.DTO.request.log.ChangeLogRequest, snapshot: com.kltn.server.DTO.request.kafka.SnapshotRequest, predict: com.kltn.server.DTO.request.kafka.SprintPredictRequest"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.kltn.server.DTO.request.log, com.kltn.server.DTO.request.kafka
            type:
              mapping: "send_mail: com.kltn.server.DTO.request.base.MailRequest, project-log: com.kltn.server.DTO.request.log.ChangeLogRequest, task-log: com.kltn.server.DTO.request.log.ChangeLogRequest, snapshot: com.kltn.server.DTO.request.kafka.SnapshotRequest, predict: com.kltn.server.DTO.request.kafka.SprintPredictRequest"
      auto-offset-reset: latest
    bootstrap-servers: localhost:9092
#    , localhost:9093, localhost:9094

server:
  address: 0.0.0.0
  port: 8080
  reactive:
    session:
      cookie:
        max-age: 5
logging:
  level:
    org:
      springframework:
        security: off
#    root: OFF
cache:
  redis:
    refresh-token:
      ttl: 432000
      key-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
      value-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
    #      hash-key-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
    #      hash-value-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
    access-token:
      ttl: 600
      key-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
      value-serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer
#      hash-key-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
#      hash-value-serializer: org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer
mail:
  sender: noreplied@gmail.com
  name: Project manager Web
app:
  ip: 192.168.1.59
  whitelist:
    - auth
    - auth/register
    - auth/refresh
    - /verify/invite-token
    - /v3/api-docs
    - /v3/api-docs/**
    - /swagger-ui/**
    - /chat/**
    - /ws/**
    - /ws
  react:
    - http://localhost:3000
    - http://localhost:5173
    - http://${app.ip}:5173
verify:
  invite-project-link: https://${app.ip}:3000/verify?token=
data:
  filepath: /home/ducvui2003/Data/university/KLTN/project/resources/data
python:
  server: http://localhost:8000/aggregate
check:
  comment: true
google:
  sheet:
    sprint:
      sheet: Sheet1
      spreadsheetId: 1TQjsIekHqYxIuronG_y_hgL0XIM1ZPV9ve7gsJwqsCQ
    issue:
      sheet: Sheet1
      spreadsheetId: 1G3NKAq6O5OyjNPbKwWvvvIfZ9RVU3otE3M8zaX_QJxU
#kafka:
#  topic:
#    send-object-customer:
#      name: send_object_customer
#      partitions: 3
#      replication-factor: 3
#    send-object-order:
#      name: send_object_order
#      partitions: 3
#      replication-factor: 3
#    send-object-product:
#      name: send_object_product
#      partitions: 3
#      replication-factor: 3
#    send-object-user:
#      name: send_object_user
#      partitions: 3
#      replication-factor: 3
