server:
  port: #REQUIRED
spring:
  application:
    name: #OPTIONAL
  datasource:
    url: #REQUIRED
  data:
    mongodb:
      uri: #REQUIRED
springdoc:
  api-docs:
    enabled: #OPTIONAL
  swagger-ui:
    enabled: #OPTIONAL
    url: #REQUIRED