spring:
  application:
    name: server
    security:
      access-token:
        time-of-life: 15m
        key:
          private-key: key/access/private_key.pem
          public-key: key/access/public_key.pem
      refresh-token:
        time-of-life: 120H
        key:
          private-key: key/refresh/private_key.pem
          public-key: key/refresh/public_key.pem

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: OpenAPI YAML
        url: /swagger.yml

server:
  reactive:
    session:
      cookie:
        max-age: 5
logging:
  level:
    org:
      springframework:
        security: off