server:
  port: #REQUIRED
spring:
  mail:
    host: #REQUIRED
    port: #REQUIRED
    username: #REQUIRED
    password: #REQUIRED
    properties:
      mail.smtp:
      auth: #REQUIRED
      starttls.enable: #REQUIRED
      ssl.trust: #REQUIRED
  application:
    name: #OPTIONAL
  datasource:
    url: #REQUIRED
  data:
    mongodb:
      uri: #REQUIRED
    redis:
      url: #REQUIRED
springdoc:
  api-docs:
    enabled: #OPTIONAL
  swagger-ui:
    enabled: #OPTIONAL
    url: #REQUIRED