openapi: 3.0.1
info:
  title: My API
  description: API documentation for my Spring Boot application
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
#  423-> email exists

  /auth:
    post:
      summary: Authenticate user
      description: Authenticates a user and returns a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '423':
          description: Invalid credentials