openapi: 3.0.1
info:
  title: My API
  description: API documentation for my Spring Boot application
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths: