# docker-compose -f db-docker-compose.yml --env-file db.env up -d

services:
  redis:
    image: 'redis:latest'
    container_name: redis_kltn
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    environment:
#      - REDIS_HOST=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - ${REDIS_VOLUME}:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb_kltn
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ${MONGO_VOLUME}:/data/db
  mysql:
    image: mysql:latest
    container_name: mysql_kltn
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: kltn
      #      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql

