@startuml
actor "Student" as Student
participant  "View\n(/manager/project/:id)" as View
participant "Issue\nController" as Controller
participant "Issue\nService" as Service
participant "Issue\nRepository" as Repository
database Database

== Access and display data ==

Student -> View : Student accesses
View -> View : Display list of sprints and product backlog
Student -> View : Select sprint to add issue
View -> View : Display add issue form
Student -> View : Fill in issue information

== Submit and process issue ==

View -> Controller : POST /issue
Controller -> Service : createIssue(issue)
Service -> Repository : jpa: save(issueModel)
Repository -> Database : save(issueModel)
Database --> Repository : return issueModel
Repository --> Service : return issueModel
Service --> Controller : return issueModel
Controller --> View : Display issue created successfully

@enduml
