@startuml
autonumber

actor "Sinh viên" as SV
participant "View\n(/manger/project/:projectId)" as View
participant "IssueController" as Controller
participant "Issue\nService" as Service
participant "Sprint\nService" as SprintService
participant "Snapshot\nService" as SnapshotService
participant "IssueRepository" as Repo
database "MySQL" as MySQL
database "MongoDB" as MongoDB

activate SV
SV -> View : Student access

activate View
View --> View : Get list sprint
SV -> View : Select sprint
View -> Controller : GET /issue/list\n?project_id=projectId\n&sprint_id=sprintId

activate Controller
Controller -> Service : get\nIssueById\n(issueId, sprintId)
activate Service
Service -> SprintService: getSprintById\n(sprintId)
activate SprintService
SprintService --> Service :  Sprint
deactivate SprintService

alt Sprint is expired
    Service -> SnapshotService : getByProject\nIdAnd\nSprintId\n(projectId, sprintId)
    activate SnapshotService
    SnapshotService -> MongoDB: getByProject\nIdAnd\nSprintId\n(projectId, sprintId)
    activate MongoDB
    MongoDB --> SnapshotService:  list issue
    deactivate MongoDB
    SnapshotService --> Service:  list issue
    deactivate SnapshotService
else
    Service -> Repo : findAllBy\nProjectId\nAndSprintId\n(projectId, sprintId)
    activate Repo
    Repo -> MySQL: findAllBy\nProjectId\nAndSprintId\n(projectId, sprintId)
    activate MySQL
    MySQL --> Repo:  list issue
    deactivate MySQL
    Repo --> Service:  list issue
    deactivate Repo
end

Service --> Controller :  list issue
deactivate Service
Controller --> View :  list issue
deactivate Controller
View --> SV : show list issue
deactivate View
deactivate SV
@enduml
