@startuml

autonumber

actor "Student" as SV

participant "View\n(/manger/project/:id)" as  View
participant "Issue\nController" as  Controller
participant "Issue\nService" as Service
participant "Issue\nRepository" as Repo
participant "Snapshot\nService" as SnapshotService
activate SV
SV -> View : Student accesses
activate View
View -> View : Display backlog\nand sprint list
SV -> View : Select sprint
View --> View: Show list issue
SV -> View: Select issue
View -> Controller : GET \n/issue/:issueId/:sprintId
activate Controller
Controller -> Service : getIssue\nDetailById\n(issueId, sprintId)
activate Service
alt Sprint is expired
    Service -> SnapshotService : getByProjectId\nAndSprintId\n(projectId, sprintId)
    activate SnapshotService
    SnapshotService -> MongoDB: getByProjectId\nAndSprintId\n(projectId, sprintId)
    activate MongoDB
    MongoDB --> SnapshotService:  list\nissue model
    deactivate MongoDB
    SnapshotService --> Service:  list issue model
    deactivate SnapshotService
    Service -> Service:  issue model
else
    Service -> Repo : getEntityById\n(projectId, sprintId)
    activate Repo
    Repo -> MySQL: findById\n(projectId, sprintId)
    activate MySQL
    MySQL --> Repo:  issue model
    deactivate MySQL
    Repo --> Service:  issue model
    deactivate Repo
end

Service --> Controller :  issueModel
deactivate Service
Controller --> View :  issue Model
deactivate Controller
View --> SV : Hiển thị chi tiết issue
deactivate View
deactivate SV
@enduml
