@startuml
autonumber
scale 2
actor "Student" as SV
participant "View\n(/manager/:id)" as View
participant "Project\nController" as Controller
participant "Project\nService" as Service
participant "Workspaces\nUsersProjects\nRepository" as WUPRepo
participant "Project\nRepository" as ProjectRepo
participant "Project\nSprint\nService" as SprintService
participant "Mongo\nService" as MongoService
participant "MySQL" as MySQL

activate SV
SV -> View : Student \n accesses

activate View
    alt Student has not\njoined a project
        View -> View : Show \n"Create Project" \n button
    else Student already has a project
        View -> View : Show "Project" \n button
    end

SV -> View : Clicks \n "Create Project"

View --> View : Show project\ncreation form
SV -> View : Submit project\ncreation form
View -> Controller : POST /project

activate Controller
Controller -> Service : createProject\n(req)
activate Service

    Service -> WUPRepo : findById\n(workspaceId, \nuserId)
    activate WUPRepo
    WUPRepo ->  MySQL : findById\n(workspaceId, userId)
    activate MySQL
    MySQL --> WUPRepo : \nworkspacesUsersProjects
    deactivate MySQL
    WUPRepo --> Service : \nworkspaces\nUsersProjects
    deactivate WUPRepo

    alt Project already exists
        Service -> Service : throw\nAppException\n(ALREADY_EXISTS)
    else No existing project

        Service -> ProjectRepo : save\n(projectEntity)
        activate ProjectRepo
        ProjectRepo -> MySQL :  save\n(projectEntity)
        activate MySQL
        MySQL --> ProjectRepo:   save\n(projectEntity)
        deactivate MySQL
        ProjectRepo --> Service : savedProject
        deactivate ProjectRepo

        Service -> SprintService : save\n(projectId, sprintIds)
        loop For each sprint \n with dtEnd
            Service -> Scheduler : scheduleSprint\nWithProject\n(sprintId, projectId,\n dtEnd)
        end

        Service -> Service: setLeader(userId)
        Service -> WUPRepo : save(project)
        activate WUPRepo
        WUPRepo --> MySQL : save(project)
        deactivate WUPRepo

        Service -> MongoService : save\n(projectMongo)
        activate MongoService
        MongoService --> Service : projectMongo \nmodel
        deactivate MongoService
    end

Service --> Controller :  \nproject model
deactivate Service
Controller --> View :  project model
deactivate Controller

View --> SV : Show \n "Create Project \n success"
deactivate View
deactivate SV

@enduml
