@startuml
autonumber

actor Student as SV
participant "View" as View
participant "Workspace\nController" as Controller
participant "Workspace\nService" as Service
participant "Workspace\nRepository" as Repo
participant "User\nService" as UService
participant "MySQL" as MySQL

activate SV
SV -> View : Student accesses\n/manager

activate View
View -> Controller : GET /workspace/list?\npage=1&size=5

activate Controller
Controller -> Service : getWorkspaceByOwnerIdPaging(req)

activate Service
Service -> UService : getCurrentUser()
activate UService
UService --> Service : return User
deactivate UService

Service -> Repo : findAllByMembersId(userId, paging)
activate Repo
Repo -> MySQL : getWorkspaceByOwnerIdPaging\n(page, size)
activate MySQL
MySQL --> Repo : return paged workspaces
deactivate MySQL
Repo --> Service : return paged workspaces
deactivate Repo

Service --> Controller : return paged workspaces
deactivate Service

Controller --> View : return paged workspaces
View --> SV : display workspace list

deactivate Controller
deactivate View
deactivate SV
@enduml
